const HINTS: Record<number, string> = {
  1: "Size and value are not the same thing.",
  2: "Read the instruction again. Carefully.",
  3: "The prompt is part of the puzzle.",
  4: "Sometimes the obvious trap is not the puzzle.",
  5: "Patience is a mechanic here.",
  6: "Punctuation counts.",
  7: "Color can move.",
  8: "Not every eight on screen is the answer.",
  9: "Empty space is not empty.",
  14: "Stay off the red lines.",
  15: "If you cannot go through, move what you can.",
  17: "This level remembers Level 16.",
  19: "The header shows where you are.",
  20: "Progress is not a button labeled SAVE.",
  25: "Match the word, not the ink.",
  28: "If the counter will never land, look at the prompt.",
  30: "You were told to forget something specific.",
  38: "Text can hide what you need.",
  39: "Keys are not always oriented correctly.",
  46: "Something flashed earlier in this run.",
  47: "Hold to inspect. Tap separately to choose.",
  48: "Stillness, after the arming period.",
  49: "Keep moving inside the puzzle area.",
  50: "The tempting button is a trap.",
  55: "Level 51 showed you a sequence.",
  60: "Exact phrase from Level 30.",
  62: "The prompt text can be dragged.",
  63: "Memorize the path before the walls vanish.",
  69: "Nothing is an answer.",
  70: "Level 69 trained you wrong.",
  76: "Not every red label means danger.",
  79: "Prove both rules in order.",
  91: "Remove the timer from the maze first.",
  92: "Only obey commands that begin correctly.",
  93: "You have seen this trick before.",
  94: "Interaction fails. Waiting wins.",
  95: "Remember what Level 94 whispered.",
  98: "The maze is not the puzzle.",
  99: "Which level number comes next?",
};

export function hintForLevel(level: number): string {
  return HINTS[level] ?? "Re-read the instruction literally.";
}
